[functions]
0x82301AA8 = { name = "start" }
0x82308FC0 = { name = "Blizzard__String__Copy" }
0x8230BF90 = { name = "Blizzard__String__Format" }
0x82311698 = { name = "Blizzard__File__Exists" }
0x82317AC0 = { name = "Blizzard__Thread__GetLocalStorage" }
0x82318138 = { name = "TlsCallback_0" }
0x8231E4B8 = { name = "Blizzard__Lock__MutexEnter" }
0x8231E4F8 = { name = "Blizzard__Lock__MutexLeave" }
0x8231EA60 = { name = "System_Using__Intern" }
0x8231EB50 = { name = "Blizzard__Using__Register" }
0x8231EB80 = { name = "Blizzard__Using__StartUsing" }
0x8231EBB0 = { name = "Blizzard__Using__StopUsing" }
0x8233D150 = { name = "CGameDisposeGame" }
0x8233D4C8 = { name = "CGameInitializeGame" }
0x8233E5F0 = { name = "ClientIdle" }
0x8236C678 = { name = "FontGroupDef__GetMaxCount" }
0x8236CAD8 = { name = "FontGroupDef__FontGroupDef" }
0x82375308 = { name = "TextureGroupDef__GetMaxCount" }
0x82375A88 = { name = "TextureGroupDef__TextureGroupDef" }
0x8237DBD8 = { name = "ShaderGroupDef__GetMaxCount" }
0x8237DE28 = { name = "ShaderGroupDef__ShaderGroupDef" }
0x823B10A8 = { name = "ClientProcessIncomingMessagesForCurrentTick" }
0x82435C40 = { name = "ShaderMapGroupDef__GetMaxCount" }
0x82435F38 = { name = "ShaderMapGroupDef__ShaderMapGroupDef" }
0x8244A1A8 = { name = "Prefs__Load" }
0x8244A4C8 = { name = "Prefs__InitializeForApp" }
0x8244D618 = { name = "Prefetch__TakeSNOElement" }
0x8244DAF0 = { name = "Prefetch__ApplyHotfix" }
0x82468230 = { name = "AppearanceGroupDef__GetMaxCount" }
0x82468510 = { name = "AppearanceGroupDef__AppearanceGroupDef" }
0x824AC498 = { name = "UIDialogGroupDef__GetMaxCount" }
0x824AC698 = { name = "UIDialogGroupDef__UIDialogGroupDef" }
0x82562E48 = { name = "WeatherGroupDef__GetMaxCount" }
0x82562EA8 = { name = "WeatherGroupDef__WeatherGroupDef" }
0x825740F8 = { name = "ControlSchemeDefinitionGroupDef__GetMaxCount" }
0x825748B0 = { name = "ControlSchemeDefinitionGroupDef__ControlSchemeDefinitionGroupDef" }
0x825AF388 = { name = "ClientMessageReceiveGameMessage" }
0x825B4B48 = { name = "LightGroupDef__GetMaxCount" }
0x825B4CE8 = { name = "LightGroupDef__LightGroupDef" }
0x825DA808 = { name = "ParticleGroupDef__GetMaxCount" }
0x825DA828 = { name = "ParticleGroupDef__ParticleGroupDef" }
0x825E9D10 = { name = "EffectGroupGroupDef__GetMaxCount" }
0x825E9D68 = { name = "EffectGroupGroupDef__EffectGroupGroupDef" }
0x825EB508 = { name = "SurfaceGroupDef__GetMaxCount" }
0x825EB558 = { name = "SurfaceGroupDef__SurfaceGroupDef" }
0x825ED588 = { name = "VibrationGroupDef__GetMaxCount" }
0x825ED630 = { name = "VibrationGroupDef__VibrationGroupDef" }
0x825ED890 = { name = "ShakeGroupDef__GetMaxCount" }
0x825ED8A0 = { name = "ShakeGroupDef__ShakeGroupDef" }
0x825EDBD0 = { name = "RopeGroupDef__GetMaxCount" }
0x825EDBE8 = { name = "RopeGroupDef__RopeGroupDef" }
0x825EDFF8 = { name = "AmbientSoundGroupDef__GetMaxCount" }
0x825EE098 = { name = "AmbientSoundGroupDef__AmbientSoundGroupDef" }
0x825EE2F0 = { name = "SoundGroupDef__GetMaxCount" }
0x825EE468 = { name = "SoundGroupDef__SoundGroupDef" }
0x825EF3A0 = { name = "SoundBankGroupDef__GetMaxCount" }
0x825EFA80 = { name = "SoundBankGroupDef__SoundBankGroupDef" }
0x825F0240 = { name = "ReverbGroupDef__GetMaxCount" }
0x825F0348 = { name = "ReverbGroupDef__ReverbGroupDef" }
0x825F05A8 = { name = "MusicGroupDef__GetMaxCount" }
0x825F0968 = { name = "MusicGroupDef__MusicGroupDef" }
0x825FEC20 = { name = "PhysicsGroupDef__GetMaxCount" }
0x825FECB0 = { name = "PhysicsGroupDef__PhysicsGroupDef" }
0x82600098 = { name = "TrailGroupDef__GetMaxCount" }
0x82600148 = { name = "TrailGroupDef__TrailGroupDef" }
0x82600F38 = { name = "ExplosionGroupDef__GetMaxCount" }
0x82600FA0 = { name = "ExplosionGroupDef__ExplosionGroupDef" }
0x82601200 = { name = "ClothGroupDef__GetMaxCount" }
0x826012C8 = { name = "ClothGroupDef__ClothGroupDef" }
0x82603D18 = { name = "MaterialGroupDef__GetMaxCount" }
0x82603D38 = { name = "MaterialGroupDef__MaterialGroupDef" }
0x8267A2F8 = { name = "Animation2DGroupDef__GetMaxCount" }
0x8267A370 = { name = "Animation2DGroupDef__Animation2DGroupDef" }
0x826B35D8 = { name = "SNOFilesGetLocalePath" }
0x826B3860 = { name = "SNOFileLoadTextFile" }
0x826B3CD0 = { name = "sApplyHotfix" }
0x826B5258 = { name = "SNOFileHeader__SNOFileHeader" }
0x826B5490 = { name = "SNOFileClose" }
0x826B5DC8 = { name = "SNOFileWriteHeader" }
0x826B5E70 = { name = "sSNOFileOpenForRead" }
0x826B6620 = { name = "SNOFileLookup" }
0x826B6810 = { name = "_SNOFileLookup" }
0x826B69F8 = { name = "SNOFileLookupGUID" }
0x826B7708 = { name = "SNOToString" }
0x826B8C00 = { name = "sSNOFileLoadLazyData" }
0x826B9090 = { name = "SNOFileOpenForRead" }
0x826B9378 = { name = "SNOFileTryGetVersion" }
0x826B99D0 = { name = "sOpenSNOPack" }
0x826B9EB0 = { name = "SNOFileAddEntry" }
0x826BAC78 = { name = "sOpenSNOPacks" }
0x826BBAC0 = { name = "SNOFilesInitialize" }
0x826BC1D8 = { name = "XTypeDescriptor__Byteswap" }
0x826C1B78 = { name = "SNOGlobals__SNOGlobals" }
0x826C2100 = { name = "GlobalSNOListRefresh" }
0x826CABD8 = { name = "AppDispose" }
0x826CB6A0 = { name = "sFileSystemInitialize" }
0x826CBC20 = { name = "sGroupDefinitionsCreateForApp" }
0x826CD6E8 = { name = "AppInitialize" }
0x826CE4F0 = { name = "AppIdle" }
0x826CECA8 = { name = "FileSystemInitializeForApp" }
0x826CF2C0 = { name = "GroupDefinition__Create_TextureGroupDef" }
0x826CF338 = { name = "GroupDefinition__Create_ShaderMapGroupDef" }
0x826CF3B0 = { name = "GroupDefinition__Create_AppearanceGroupDef" }
0x826CF428 = { name = "GroupDefinition__Create_PhysMeshGroupDef" }
0x826CF4A0 = { name = "GroupDefinition__Create_GlobalGroupDef" }
0x826CF518 = { name = "GroupDefinition__Create_ObserverGroupDef" }
0x826CF590 = { name = "GroupDefinition__Create_SceneGroupDef" }
0x826CF608 = { name = "GroupDefinition__Create_WorldGroupDef" }
0x826CF680 = { name = "GroupDefinition__Create_ActorGroupDef" }
0x826CF6F8 = { name = "GroupDefinition__Create_AnimSetGroupDef" }
0x826CF770 = { name = "GroupDefinition__Create_AnimationGroupDef" }
0x826CF7E8 = { name = "GroupDefinition__Create_StringListGroupDef" }
0x826CF860 = { name = "GroupDefinition__Create_ScriptGroupDef" }
0x826CF8D8 = { name = "GroupDefinition__Create_PowerGroupDef" }
0x826CF950 = { name = "GroupDefinition__Create_MarkerSetGroupDef" }
0x826CF9C8 = { name = "GroupDefinition__Create_HeroGroupDef" }
0x826CFA40 = { name = "GroupDefinition__Create_GameBalanceGroupDef" }
0x826CFAB8 = { name = "GroupDefinition__Create_EncounterGroupDef" }
0x826CFB30 = { name = "GroupDefinition__Create_AdventureGroupDef" }
0x826CFBA8 = { name = "GroupDefinition__Create_ConversationGroupDef" }
0x826CFC20 = { name = "GroupDefinition__Create_ConversationListGroupDef" }
0x826CFC98 = { name = "GroupDefinition__Create_FlagSetGroupDef" }
0x826CFD10 = { name = "GroupDefinition__Create_SceneGroupGroupDef" }
0x826CFD88 = { name = "GroupDefinition__Create_LevelAreaGroupDef" }
0x826CFE00 = { name = "GroupDefinition__Create_QuestGroupDef" }
0x826CFE78 = { name = "GroupDefinition__Create_QuestRangeGroupDef" }
0x826CFEF0 = { name = "GroupDefinition__Create_ConductorGroupDef" }
0x826CFF68 = { name = "GroupDefinition__Create_SkillKitGroupDef" }
0x826CFFE0 = { name = "GroupDefinition__Create_MonsterGroupDef" }
0x826D0058 = { name = "GroupDefinition__Create_AIStateGroupDef" }
0x826D00D0 = { name = "GroupDefinition__Create_AIBehaviorGroupDef" }
0x826D0148 = { name = "GroupDefinition__Create_RecipeGroupDef" }
0x826D01C0 = { name = "GroupDefinition__Create_TimedEventGroupDef" }
0x826D0238 = { name = "GroupDefinition__Create_ActGroupDef" }
0x826D02B0 = { name = "GroupDefinition__Create_LoreGroupDef" }
0x826D0328 = { name = "GroupDefinition__Create_ConditionGroupDef" }
0x826D03A0 = { name = "GroupDefinition__Create_AccountGroupDef" }
0x826D0418 = { name = "GroupDefinition__Create_TreasureClassGroupDef" }
0x826D0490 = { name = "GroupDefinition__Create_BossEncounterGroupDef" }
0x826D0508 = { name = "GroupDefinition__Create_TutorialGroupDef" }
0x826D0580 = { name = "GroupDefinition__Create_AccoladeGroupDef" }
0x826D05F8 = { name = "GroupDefinition__Create_AmbientSoundGroupDef" }
0x826D0670 = { name = "GroupDefinition__Create_PhysicsGroupDef" }
0x826D06E8 = { name = "GroupDefinition__Create_ExplosionGroupDef" }
0x826D0760 = { name = "GroupDefinition__Create_SurfaceGroupDef" }
0x826D07D8 = { name = "GroupDefinition__Create_EffectGroupGroupDef" }
0x826D0850 = { name = "GroupDefinition__Create_ClothGroupDef" }
0x826D08C8 = { name = "GroupDefinition__Create_TrailGroupDef" }
0x826D0940 = { name = "GroupDefinition__Create_ParticleGroupDef" }
0x826D09B8 = { name = "GroupDefinition__Create_FontGroupDef" }
0x826D0A30 = { name = "GroupDefinition__Create_Animation2DGroupDef" }
0x826D0AA8 = { name = "GroupDefinition__Create_ShaderGroupDef" }
0x826D0B20 = { name = "GroupDefinition__Create_UIDialogGroupDef" }
0x826D0B98 = { name = "GroupDefinition__Create_LightGroupDef" }
0x826D0C10 = { name = "GroupDefinition__Create_SoundBankGroupDef" }
0x826D0C88 = { name = "GroupDefinition__Create_SoundGroupDef" }
0x826D0D00 = { name = "GroupDefinition__Create_MusicGroupDef" }
0x826D0D78 = { name = "GroupDefinition__Create_RopeGroupDef" }
0x826D0DF0 = { name = "GroupDefinition__Create_WeatherGroupDef" }
0x826D0E68 = { name = "GroupDefinition__Create_ShakeGroupDef" }
0x826D0EE0 = { name = "GroupDefinition__Create_VibrationGroupDef" }
0x826D0F58 = { name = "GroupDefinition__Create_MaterialGroupDef" }
0x826D0FD0 = { name = "GroupDefinition__Create_ReverbGroupDef" }
0x826D1048 = { name = "GroupDefinition__Create_ControlSchemeDefinitionGroupDef" }
0x826D10C0 = { name = "GroupDefinition__Create_AnimTreeGroupDef" }
0x826DC4A8 = { name = "GroupDefinition__sReportBadDataToUser" }
0x826DD080 = { name = "RequiredDefinitionHeader__RequiredDefinitionHeader" }
0x826DD118 = { name = "GroupDefinition__GetFallbackDataSNO" }
0x826DD960 = { name = "GroupDefinition__GroupDefinition" }
0x826DDD78 = { name = "GroupDefinition__SNOWriteSNOFile" }
0x826DF108 = { name = "GroupDefinition__SetDefinition" }
0x826DF228 = { name = "GroupDefinition__sCreate" }
0x826DFB78 = { name = "GroupDefinition__Init" }
0x826E0858 = { name = "GroupDefinition__sLoad" }
0x826E0FF0 = { name = "GroupDefinition__New" }
0x826E1348 = { name = "GroupDefinition__LockR" }
0x826E2258 = { name = "ThreadSafeDef__ThreadSafeDef" }
0x826E3C08 = { name = "TDataArrayCreateTracked_DefDataElement_DefDataElementID" }
0x826E3CA8 = { name = "TDataArrayCreateTracked_PendingDefDataElement_DefDataElementID" }
0x826E46D0 = { name = "StringListGroupDef__GetMaxCount" }
0x826E4D70 = { name = "StringListGroupDef__StringListGroupDef" }
0x82733980 = { name = "KeyGetCompressor" }
0x8273DAE8 = { name = "GameBalanceGroupDef__GetMaxCount" }
0x8273E400 = { name = "GameBalanceGroupDef__GameBalanceGroupDef" }
0x827410E8 = { name = "WorldGroupDef__GetMaxCount" }
0x82741248 = { name = "WorldGroupDef__WorldGroupDef" }
0x8276FAD8 = { name = "SubsystemsDispose" }
0x8276FB40 = { name = "SubsystemsInitialize" }
0x82780310 = { name = "Console__IO__OpenArchive" }
0x8278BF38 = { name = "XDecoder__Get" }
0x8278F260 = { name = "TypeDescriptorClass_DT_INT__Encode" }
0x8278F2F8 = { name = "TypeDescriptorClass_DT_INT__Decode" }
0x82791AB8 = { name = "SFileOpenArchive" }
0x82791E88 = { name = "SNOMLInternal_Initialize" }
0x82792080 = { name = "SNOMLFileOpenForRead" }
0x82792090 = { name = "SNOMLGetAssetVersion" }
0x827923F8 = { name = "ObserverGroupDef__GetMaxCount" }
0x82792408 = { name = "ObserverGroupDef__ObserverGroupDef" }
0x827C1618 = { name = "ActGroupDef__GetMaxCount" }
0x827C1690 = { name = "ActGroupDef__ActGroupDef" }
0x827C1A18 = { name = "AccountGroupDef__GetMaxCount" }
0x827C1AB0 = { name = "AccountGroupDef__AccountGroupDef" }
0x827C2A68 = { name = "HeroGroupDef__GetMaxCount" }
0x827C2CF8 = { name = "HeroGroupDef__HeroGroupDef" }
0x827CEB90 = { name = "MarkerSetGroupDef__GetMaxCount" }
0x827CEBB8 = { name = "MarkerSetGroupDef__MarkerSetGroupDef" }
0x827CF6A0 = { name = "GlobalGroupDef__GetMaxCount" }
0x827CF788 = { name = "GlobalGroupDef__GlobalGroupDef" }
0x827D1FB0 = { name = "ActorGroupDef__GetMaxCount" }
0x827D2138 = { name = "ActorGroupDef__ActorGroupDef" }
0x827D2B80 = { name = "PowerGroupDef__GetMaxCount" }
0x827D2C48 = { name = "PowerGroupDef__PowerGroupDef" }
0x827E9210 = { name = "LevelAreaGroupDef__GetMaxCount" }
0x827E9480 = { name = "LevelAreaGroupDef__LevelAreaGroupDef" }
0x827ED6F8 = { name = "GetGameMessageTypeAndSize" }
0x827EF160 = { name = "EncodeMessage" }
0x827EF2A0 = { name = "DecodeMessage" }
0x827EF6E8 = { name = "GameMessageTypeToName" }
0x827EF978 = { name = "MonsterGroupDef__GetMaxCount" }
0x827EFAE0 = { name = "MonsterGroupDef__MonsterGroupDef" }
0x827EFD50 = { name = "AnimTreeGroupDef__GetMaxCount" }
0x827EFDB0 = { name = "AnimTreeGroupDef__AnimTreeGroupDef" }
0x827F05E0 = { name = "EncounterGroupDef__GetMaxCount" }
0x827F05F0 = { name = "EncounterGroupDef__EncounterGroupDef" }
0x827F5C78 = { name = "AnimationGroupDef__GetMaxCount" }
0x827F6F68 = { name = "AnimationGroupDef__AnimationGroupDef" }
0x827F9808 = { name = "SceneGroupDef__GetMaxCount" }
0x827FA5C8 = { name = "SceneGroupDef__SceneGroupDef" }
0x827FA948 = { name = "SceneGroupGroupDef__GetMaxCount" }
0x827FA958 = { name = "SceneGroupGroupDef__SceneGroupGroupDef" }
0x82800F18 = { name = "QuestRangeGroupDef__GetMaxCount" }
0x828010E8 = { name = "QuestRangeGroupDef__QuestRangeGroupDef" }
0x82801CE0 = { name = "PhysMeshGroupDef__GetMaxCount" }
0x82801D80 = { name = "PhysMeshGroupDef__PhysMeshGroupDef" }
0x82812758 = { name = "SNOFilesGetAsyncStatus" }
0x82812DD0 = { name = "SNOFilesAsyncIsLocking" }
0x82816978 = { name = "AnimSetGroupDef__GetMaxCount" }
0x828169C8 = { name = "AnimSetGroupDef__AnimSetGroupDef" }
0x828256B8 = { name = "ConversationGroupDef__GetMaxCount" }
0x82825F08 = { name = "ConversationGroupDef__ConversationGroupDef" }
0x82827748 = { name = "LoreGroupDef__GetMaxCount" }
0x828277A0 = { name = "LoreGroupDef__LoreGroupDef" }
0x82828310 = { name = "QuestGroupDef__GetMaxCount" }
0x82828920 = { name = "QuestGroupDef__QuestGroupDef" }
0x82829418 = { name = "SkillKitGroupDef__GetMaxCount" }
0x82829478 = { name = "SkillKitGroupDef__SkillKitGroupDef" }
0x8282F258 = { name = "TutorialGroupDef__GetMaxCount" }
0x8282F2A8 = { name = "TutorialGroupDef__TutorialGroupDef" }
0x8282F588 = { name = "RecipeGroupDef__GetMaxCount" }
0x8282F5F0 = { name = "RecipeGroupDef__RecipeGroupDef" }
0x82875608 = { name = "AttributeCompressor__Encode" }
0x82875670 = { name = "AttributeCompressor__Decode" }
0x82877FC0 = { name = "SNOGroupComparator" }
0x82877FD0 = { name = "SNOGroupsInitialize" }
0x82878008 = { name = "SNOGroupsDispose" }
0x82878190 = { name = "GameXMLDefinitionsGet" }
0x828781D8 = { name = "SNOGroupGetInfo" }
0x82878238 = { name = "SNOGroupGetName" }
0x82878328 = { name = "SNOGroupRegister" }
0x8287FE68 = { name = "BossEncounterGroupDef__GetMaxCount" }
0x8287FF08 = { name = "BossEncounterGroupDef__BossEncounterGroupDef" }
0x828801B8 = { name = "SNOTOC__GetMPQFilename" }
0x828802E8 = { name = "SNOTOC__GetLooseFilename" }
0x82880570 = { name = "SNOTOC__ReadTOC" }
0x82880648 = { name = "SNOTOC__Read" }
0x82880B40 = { name = "SNOTOC__ApplyHotfix" }
0x82880C68 = { name = "SNOTOC__ReadIntoFileTable" }
0x82881128 = { name = "blz__vector_SNOEntry__ctor" }
0x828813B8 = { name = "SNOMLGetTypeFromClassName" }
0x82881450 = { name = "SNOMLInitialize" }
0x82881760 = { name = "SNOMLGetTypeFromSNOGroup" }
0x82882030 = { name = "AccoladeGroupDef__GetMaxCount" }
0x82882080 = { name = "AccoladeGroupDef__AccoladeGroupDef" }
0x828822E0 = { name = "TreasureClassGroupDef__GetMaxCount" }
0x82882668 = { name = "TreasureClassGroupDef__TreasureClassGroupDef" }
0x82882A08 = { name = "ConditionGroupDef__GetMaxCount" }
0x82882D48 = { name = "ConditionGroupDef__ConditionGroupDef" }
0x828836C8 = { name = "TimedEventGroupDef__GetMaxCount" }
0x828836E8 = { name = "TimedEventGroupDef__TimedEventGroupDef" }
0x82883948 = { name = "FlagSetGroupDef__GetMaxCount" }
0x82883B88 = { name = "FlagSetGroupDef__FlagSetGroupDef" }
0x82883FE0 = { name = "ConversationListGroupDef__GetMaxCount" }
0x82884070 = { name = "ConversationListGroupDef__ConversationListGroupDef" }
0x82884B88 = { name = "AdventureGroupDef__GetMaxCount" }
0x82884BC0 = { name = "AdventureGroupDef__AdventureGroupDef" }
0x828D0428 = { name = "AIBehaviorGroupDef__GetMaxCount" }
0x828D0430 = { name = "AIStateGroupDef__GetMaxCount" }
0x828D0470 = { name = "AIBehaviorGroupDef__AIBehaviorGroupDef" }
0x828D0530 = { name = "AIStateGroupDef__AIStateGroupDef" }
0x828D09C8 = { name = "ConductorGroupDef__GetMaxCount" }
0x828D0F70 = { name = "ConductorGroupDef__ConductorGroupDef" }
0x828D2128 = { name = "ScriptGroupDef__GetMaxCount" }
0x828D2530 = { name = "ScriptGroupDef__ScriptGroupDef" }
0x828DA598 = { name = "SGameInitializeGame" }
0x828DAA28 = { name = "SGameDisposeGame" }
0x82A72D40 = { name = "ExitProgram" }
0x82A73458 = { name = "DisplayErrorMessage" }
0x82A735E8 = { name = "SigmaCurrentlyHandlingError" }
0x82A738C8 = { name = "DisplayInternalError" }
0x82A73D00 = { name = "ErrorManagerInitialize" }
0x82A74A00 = { name = "CRefString__str" }
0x82A74CE8 = { name = "CRefString__CRefString" }
0x82A75500 = { name = "CRefString__dtor_CRefString" }
0x82A75D30 = { name = "CRefString__Format" }
0x82A76448 = { name = "CRefString__operator_assign_char" }
0x82A77398 = { name = "sSigmaMemoryReallyDispose" }
0x82A77408 = { name = "SigmaMemorySetTraceAllocations" }
0x82A77460 = { name = "SigmaMemoryFree" }
0x82A774A8 = { name = "SigmaMemoryCopy" }
0x82A774B8 = { name = "SigmaMemoryClear" }
0x82A776A8 = { name = "sSigmaMemoryInit" }
0x82A77980 = { name = "SigmaMemoryInit" }
0x82A77A40 = { name = "SigmaMemoryNew" }
0x82A77BC0 = { name = "operator_new" }
0x82A78220 = { name = "SigmaInit" }
0x82A78B38 = { name = "ErrorManagerSetLogStreamFilename" }
0x82A7C100 = { name = "Blizzard__Memory__Shutdown" }
0x82A7C348 = { name = "XFourCC__StringToValue" }
0x82A7F210 = { name = "FileReference__FileReference" }
0x82A7F298 = { name = "FileReferenceGetPath" }
0x82A7F468 = { name = "FileExists" }
0x82A7F6D0 = { name = "FileWrite" }
0x82A7FA30 = { name = "FileReferenceInit" }
0x82A82C38 = { name = "XLocaleToString" }
0x82A82CE8 = { name = "UnicodeText__SetLocale" }
0x82A82CF8 = { name = "UnicodeText__GetCurrentLocale" }
0x82A8DC00 = { name = "TypeDescriptorField__TypeDescriptorField_Dynamic" }
0x82A8DE18 = { name = "TypeDescriptorField__TypeDescriptorField" }
0x82A8DFA8 = { name = "FixedArrayTypeDescriptorField__FixedArrayTypeDescriptorField" }
0x82A8DFE8 = { name = "VariableArrayTypeDescriptorField__VariableArrayTypeDescriptorField" }
0x82A8E108 = { name = "EnumTypeDescriptorField__EnumTypeDescriptorField" }
0x82A8E420 = { name = "SymbolToName" }
0x82A97000 = { name = "LanguageRules__InitializeDeclensions" }
0x82A977E0 = { name = "XEncoder__SetUsed" }
0x82A97818 = { name = "XEncoder__PutAligned8" }
0x82A97890 = { name = "XEncoder__Put" }
0x82A97AE0 = { name = "XEncoder__PutBytesAligned8" }
0x82A97EB0 = { name = "XDecoder__GetAligned8" }
0x82A97F48 = { name = "XDecoder__GetBytesAligned8" }
0x82A98818 = { name = "DataArrayTrackerInit" }
0x82AA0A10 = { name = "XVarInitialize" }
0x82AA59A0 = { name = "ErrorManagerBlizzardErrorData__AddMetadata" }
0x82AAA700 = { name = "Blizzard__String__MemCopy" }
0x82AAFB58 = { name = "_sprintf" }
0x82F868A0 = { name = "GLOBAL__sub_I_UnicodeText_cpp" }
